### ISSUE TITLE
Evaluate core XDR change impact for adding ContractCostType::ChaCha20DrawBytes

### ISSUE THREAD

**Issue by anupsdf** [stellar/soroban-tools#1000]
### What?
Evaluate the impact of Core XDR ContractCostType::ChaCha20DrawBytes changes in https://github.com/stellar/stellar-xdr/commit/f2f213cf502c73cdac5bb8aa59de9102494e965e

**Comment by tamirms** [comment]
I don't think we need to do anything specifically for this change or https://github.com/stellar/soroban-tools/issues/1001 because we do not construct `ContractCostType` xdr values in either horizon or soroban-rpc. I think the only work required is updating the xdr definitions in the go monorepo and then bumping the go monorepo dependency in soroban-rpc.

I think the work for updating the xdr definitions can be pointed as a 3 (https://github.com/stellar/go/issues/4788 is a similar issue from the past which can be used as a reference point).

**Comment by mollykarcher** [comment]
Closing in favor of https://github.com/stellar/go/issues/5075
