### ISSUE TITLE
CLI: Auth Next Support

### ISSUE THREAD

**Issue by chadoh** [stellar/soroban-tools#360]
Soroban's [Auth Next](https://docs.google.com/document/d/1J-J3ClTUkrsLiJag906OH4hmNkZI3Jk6_Y9ZYt_psAI/edit#heading=h.mne05sjh63jf) feature is shaping up. The current idea is to supersede the `invoker` pattern, `soroban-auth`, and custom auth with a new, more-flexible approach.

As an example, let's consider two contract methods:

```rs
pub fn set_state(env: Env, acc: Account, state: State) {}

pub fn swap(env: Env, acc1: Account, acc2: Account, ...) {}
```

The idea here is that there is no implicit "invoker" added to `env`, but instead, anytime a smart contract author wants to require a signature from a given account, they use the Account type for one or more arguments. So `set_state` requires one signing account, but `swap` requires two. We could even imagine a function that requires an arbitrary number of signatures:

```rs
pub fn foo(env: Env, accs: Vec<Account>) {}
```

Each of these Account args have a complex structure, and would need to be passed as a JSON object looking something like:

```json
{"identity": "my_id", "invocations": [{ "contract_id": "C...", "function": "set_state", "args": [{"state": {...}]}
```

# Making this usable from the CLI

We have the prerequisites we need to add developer-friendly support for Auth Next to the CLI:

- #275
- #307

To start with, the CLI can allow passing all of this explicitly. Using the `set_state` example from above:

```bash
soroban invoke --contract-id $ID --fn set_state -- --acc '{ "identity": "my_id", "invocations": ... }' --state '{ ... }'
```

But paired with the `soroban config identity` feature (#275), it can also support passing Accounts implicitly. Perhaps this could look like:

```bash
soroban invoke --contract-id $ID --fn set_state -- --acc identity:chadoh --state '{ ... }'
```

Here, the "implicit CLI" built by `invoke` would check if the argument is a string prepended with "identity", and would perform the logic & preflight calls necessary to expand that argument into the full JSON structure expected by the smart contract.

Since we have full control over the implicit invoke CLI, we can build this in whatever best optimizes both maintenance and UX. Some other examples of how this might look, using the `swap` example from above:

```bash
# prefixed with `identity:`, as above
soroban invoke --contract-id $ID --fn swap -- --acc1 identity:chadoh --acc2 identity:ahalabs

# prefixed with just `id:`
soroban invoke --contract-id $ID --fn swap -- --acc1 id:chadoh --acc2 id:ahalabs

# maybe no prefix is necessary?
soroban invoke --contract-id $ID --fn swap -- --acc1 chadoh --acc2 ahalabs
```

**Comment by paulbellamy** [comment]
Summarizing our discussion today...

We also need to include the sender for the txn. Currently that's done via the `--identity` flag. Maybe we should:
- Rename the `--identity` flag to a `--source` flag
- Use a prefix everywhere, for identities: `--source identity:chadoh` (or auto-infer? see above)
- Support public/secret keys everywhere we support identities.

A few examples:

### Use a specific secret key to send a txn.
Pretty standard. No auth-next required.
`soroban invoke --contract-id $ID --fn symbol --source S123...456`
    
### Use an unsigned address as an `Address` arg to the contract to read balance
The `G123...456` account is not a signing identity, just a public address, so this would fail if the preflight says the `acc` arg must be signed. Txn is sent as `chadoh`.
`soroban invoke --source identity:chadoh --contract-id $ID --fn balance -- --acc G123....456`
    
### Transfer 5 stroops of an asset from chadoh to G123...456.
In this case there is only a single signing identity (`chadoh`), used for both the source account, and the single signed `Address` needed for the `xfer` method. The preflight would only return a single required `ContractAuth`, which is matched with the available `chadoh` signing identity.
Txn source account is `chadoh` (but could be different from the `from` flag).

`soroban invoke --contract-id $ID --fn xfer --source identity:chadoh -- --from identity:chadoh --to G123...456 --amount 5`
    
### Complicated multi-sig atomic swap, between willem (a local identity) and a secret key
Txn source account is `chadoh`.

```
soroban invoke \
  --contract-id $ID --fn swap \
  --source identity:chadoh \
  -- \
  --acc1 identity:willem --acc2 S123...456 \
  --token1 foo           --token2 bar \
  --amount1 5            --amount2 10
```

CLI would call the preflight, see that the callstack needs 2 ContractAuths (one for `willem`, and one for `S123...456`). It would collect the signing identities it has available, and use them to sign the relevant ContractAuths. Then it would sign the whole transaction as `chadoh` and submit the txn.

---
    
(Note: for now, this ignores any attempt to show the user what they are signing, and just blindly signs)

Is that accurate, @dmkozh ? Or are there any missing cases we need to handle?

**Comment by dmkozh** [comment]
Thanks for writing this up!

> Rename the --identity flag to a --source flag
This should also be combined with removing --account flag (or using --account name instead of --source)

>Pretty standard. No auth-next required.
soroban invoke --contract-id $ID --fn symbol --source S123...456

What is your expectation here in terms of the source account of the transaction?

> soroban invoke --source identity:chadoh --contract-id $ID --fn balance -- --acc G123....456

This probably should succeed if `balance` requires auth from `acc` and `acc` public key belongs to identity:chadoh (this will happen automatically as long as preflight returns the auth payload for invoker, i.e. missing address and nonce).

The rest of examples look good.

>Or are there any missing cases we need to handle?

The only other thing I've mentioned is a case when auth is required from an identity that is not passed explicitly. For example:

`soroban invoke --contract-id $ID --fn mint--source identity:chadoh --additional-signers identity:token-admin -- --to G123...456 --amount 5`

This will allow to authorize the token admin to authorize the `mint` call even though `mint` itself doesn't need to have `admin` to be passed to the invocation. The semantics would be basically 'if preflight returns a payload corresponding to the address from `additional-signer`, use their secret key or identity to do the signing'.

One more idea for a possible QOL improvement that can go side-by-side with --additional-signers: we could instead treat *all* the known identities as 'additional signers'. That is, if preflight returns an address for which we have a secret key, just sign it. In this scenario (and probably in all the other scenarios) a prompt like 'you are about to sign something on behalf of [identity:chadoh, identity:token-admin]. Proceed? y/n' would be great to have (though maybe unnecessary outside of pubnet).

**Comment by paulbellamy** [comment]
> What is your expectation here in terms of the source account of the transaction?

My expectation is that it would set the source account of the transaction. I'm not sure what else you could mean?

>  ... `--additional-signers` ...

Makes sense, and seems like a good extra flag. In general I'd steer away from using identities which have not been explicitly specified in the CLI, but the warning is tempting... thoughts @willemneal / @chadoh ?

**Comment by dmkozh** [comment]
> My expectation is that it would set the source account of the transaction. I'm not sure what else you could mean?

Sorry, I haven't realized we don't pass any arguments to the function invocation. That looks good to me then.

**Comment by dmkozh** [comment]
@paulbellamy, is this really fully completed? The PR seems to only address the source accounts; was the support for other features (like additional signers, using identities as addresses etc.) added in some other PRs?
