### ISSUE TITLE
[epic] Platform mid March release

### ISSUE THREAD

**Issue by tsachiherman** [stellar/soroban-tools#471]
This epic contains all the upcoming core features that needs to be supported by the platform team:
* ~~[Network Config Ledger Entries](https://github.com/stellar/soroban-tools/issues/519)~~
* Diagnostic Events
* Object Reform / Value Overhaul

### Diagnostics Events ( 11 points + 17 days)
* #476 (3 days)
* https://github.com/stellar/js-soroban-client/issues/59 (3 days)
* https://github.com/stellar/system-test/issues/40 (5 days)
* #474 (3 points)
* https://github.com/stellar/quickstart/issues/436
* https://github.com/stellar/go/issues/4789 (3 points)
* #473 (2 points)
* https://github.com/stellar/quickstart/issues/434 (3 days)
* #472 (3 points)
* #475 (3 days)

### Object Reform / Value Overhaul ( 12 points + 8 days )
* Docs: update documentation to reflect this change (3 days)
* https://github.com/stellar/soroban-example-dapp/issues/92 (5 points)
* https://github.com/stellar/system-test/issues/41 (2 points)
* https://github.com/stellar/soroban-tools/issues/479 (2 days)
* https://github.com/stellar/go/issues/4790 (5 points)
* https://github.com/stellar/soroban-tools/issues/481 (1 days)
* https://github.com/stellar/soroban-tools/issues/482 (2 days)
* https://github.com/stellar/soroban-tools/issues/477 (2 points)
* https://github.com/stellar/js-soroban-client/issues/60 (1 points)
* https://github.com/stellar/js-stellar-base/issues/581 (2 points)
* https://github.com/stellar/soroban-tools/issues/478 (13 days)
* https://github.com/stellar/soroban-tools/issues/480 (2 days)
* soroban-cli: #462  (3 days)
* https://github.com/stellar/go/issues/4792 (2 points)
* https://github.com/stellar/go/issues/4791 (2 point)

**Comment by sisuresh** [comment]
I just realized something - There should be no required work from the platform team for Network Config Ledger Entries this release because we don't actually use those entries anywhere at the moment. The core change in this release introduces a mechanism to update the Network Config Ledger Entries, but they have not been hooked up to soroban yet. In the next release, one of these entries will be used for metering, which is when I expect the work mentioned here will be required. Apologies for not catching this earlier.
