### ISSUE TITLE
soroban-cli: output diagnostic events from CLI

### ISSUE THREAD

**Issue by tsachiherman** [stellar/soroban-tools#476]
### What ?

soroban-cli: output debug events from CLI

### Epic

https://github.com/stellar/soroban-tools/issues/471

**Comment by 2opremio** [comment]
I presume this only refers to `soroban invoke` since we have a specific ticket for getting the events ( https://github.com/stellar/soroban-tools/issues/473 )

As a result of this ticket `soroban invoke` should:

1. Print the debug events of `simulateTransaction`
2. Print the debug events when sending the transaction (`sendTransaction`). This may require some syncing with soroban-rpc.

I am not sure whether (1) is useful if the transaction submission succeeds (since I presume the debug events will be identical)

We may or may not want to print the debug events of `soroban deploy` (which also submits a transaction which may generates events).

**Comment by tsachiherman** [comment]
I agree that int he case of `soroban invoke`, it might not be very useful to see the debug events output of the `simulateTransaction`. However, I think that we missed something here : we should create a ticket for adding support returning debug events from `sendTransaction`, right ?

**Comment by 2opremio** [comment]
I don’t think `sendTransaction` can output events directly. I think we would need for txmeta to arrive after the transaction is included.

@tamirms isn't that the case?
