### ISSUE TITLE
version, --version, -V, -v weirdness

### ISSUE THREAD

**Issue by tyvdh** [stellar/soroban-tools#795]
```bash
% soroban -V
soroban 0.9.1 (339cc91f6db1752fed4220df2a2fafe499644fbf)
```
```bash
% soroban --version
soroban 0.9.1 (339cc91f6db1752fed4220df2a2fafe499644fbf)
soroban-env 0.0.17 (400d806387140553e4e685d232deb3a807ec0e36)
soroban-env interface version 85899345971
stellar-xdr 0.0.17 (0f16673441898162c9996da6117be2280ef8fd84)
```

`-V` vs `-v` seems like an anti-pattern. If we want to shorten the `--verbose` command it should be `-V` and `-v` should be version and it should always print out all the version not just the `soroban` cli version.

**Comment by willemneal** [comment]
-v is short of --verbose. I think we should get rid of -V. But I think it is strange that --version differs from the subcommand. However, I think is is difficult because the flag is autogenerate by clap and the other requires build time info.

**Comment by stellarsaur** [comment]
Ideally, we would replace `-V` with `-v` and have the behavior of `-v` be consistent with `soroban version` and `soroban --version`.

**Comment by leighmcculloch** [comment]
> `-V` vs `-v` seems like an anti-pattern

This is a common pattern in plenty of tools, take `curl`, and `rustc`, `cargo`, and it's the default behavior when using `clap` CLI framework, which we're using.

I think this issue is pretty low impact. But for the sake of having one way to do version in soroban-cli, I suggest we remove `-V` and `--version` so that the only way to get the version info is with the `version` subcommand. It keeps the behavior consistent with the overall pattern of behavior of the soroban-cli, where commands are designed around a subcommand triggering behavior, and options modifying that behavior. And it keeps it behaving consistently with the command line interfaces of other Stellar software. For example, stellar-core, stellar-xdr, soroban-rpc, and horizon all behave this way.

The change required is minimal:
```diff
--- a/cmd/soroban-cli/src/commands/mod.rs
+++ b/cmd/soroban-cli/src/commands/mod.rs
@@ -45,11 +45,10 @@ Full CLI reference: https://github.com/stellar/soroban-tools/tree/main/docs/soro
 #[derive(Parser, Debug)]
 #[command(
     name = "soroban",
-    version = version::short(),
-    long_version = version::long(),
     about = ABOUT,
     long_about = ABOUT.to_string() + LONG_ABOUT,
     disable_help_subcommand = true,
+    disable_version_flag = true,
 )]
 pub struct Root {
     #[clap(flatten)]
```
