### ISSUE TITLE
soroban-rpc: Transaction simulation should assist in determining state expiration

### ISSUE THREAD

**Issue by Shaptic** [stellar/soroban-tools#803]
### What problem does your feature solve?
It can be hard (and slow) to determine when and what to restore when a transaction simulation fails due to expired ledger entries. More specifically, if you run `simulateTransaction()` and encounter a failure, you have to do a bunch of extra work to determine whether or not it's related to state expiration AND figure out which ledgers need to be restored.

### What would you like to see?
An amendment to the `simulateTransaction` response schema:

```diff
+  expiredEntries: string[];
+  restorationFootprint: string;
```

which would be:
 * a list of base64-encoded `xdr.LedgerKey` instances corresponding to entries that the system knows have expired at the time of the simulation
 * a base64-encoded `xdr.SorobanTransactionData` instance that would correspond to a `restoreFootprintOp` transaction's `sorobanData` field (fee info, etc.), so that the client can immediately submit a restoration transaction (without running a sim)

### What alternatives are there?
I don't think there is one. **IF** (and this is a big "if") you have the relevant `xdr.LedgerKey[]`s already, you can

 1. call `getLedgerEntries` to acquire the `xdr.LedgerEntry[]`s that have expired
 3. you then parse+compare that response to determine which `restoreFootprintOp`s are needed

However, this is problematic for several reasons:
 * there is extra latency due to the additional request+processing
 * that extra latency can introduce edge cases in ledger expiration timing
 * **you still need the keys**, which is not feasible without, I dunno, storing all of your tx envelopes client-side

**Comment by 2opremio** [comment]
I am not sure we can implement this without changes to the [soroban-env-host](https://github.com/stellar/rs-soroban-env/tree/main/soroban-env-host) library.

Let me explain. Host function preflighting works by trying to execute a host function (through  the `soroban-env-host` library) and recording what ledger entries have been accessed.

When a host function executes, it needs to access ledger entries. To do so, soroban-rpc plugs its ledger storage into `soroban-env-host`.

Although soroban-rpc stores all ledger entries (expired or not) it hides expired ledger entries during host function execution to simulate what really would happen when the preflighted transaction is submitted.

Thus, in the eyes of `soroban-env-host` when the host function tries to access an expired entry, it will simply think it's missing. Leading to missing entry errors.

Now, what we could _maybe_ do is stop hiding expired entries to `soroban-env-host`  and somehow figure out whether the computed ledger-footprint contains expired entries after executing the host function.

However, I don't know if that would be safe or whether it would work:

1. Does the Host check the ledger entry expirations? (if this is the case, then it doesn't matter whether we hide expired or not)
2. Can we safely tell which entries would had required restoring? It's obvious that any expired entry in the readonly footprint would require expiring. But how about the readwrite footprint? Maybe the contract could had written fresh entry with the same key without requiring an explicit restore.

**Comment by 2opremio** [comment]
> MVP: at least finding one ledger key that has expired at a time
> 
> You would need to resubmit to find other expired ledger entries in the set.

This should certainly be possible, provided that `soroban-env-host`  gives us an identifiable error from which we can extract which ledger entry is missing.

I don't think we have that today, do we @dmkozh ?

**Comment by 2opremio** [comment]
I think it’s going to be feasible, since contracts can’t know whether a persistent entry expired or not.

**Comment by dmkozh** [comment]
My general comment on this would be that host operates on a **valid** snapshot of ledger and produces a set of changes to it. One of the criteria for being 'valid' is that none of the entries have expired. That means that snapshot provider can inject whatever logic feasible. Core fails transaction when an expired entry is encountered, and preflight snapshot provider can just 'recover' the expired entry automatically and take a note of that. As long as host sees valid ledger entries in the snapshot, everything should work just fine. This will also allow collecting all the expired entries on the code path, as long as they're accessible in some way in the preflight snapshot.

**Comment by tsachiherman** [comment]
@dmkozh so, if I understand you correctly, you're suggesting the following:
- The soroban-rpc would treat all entries as "live" entries.
- Throughout the simulation, the soroban-rpc would "record" the entries that have been accessed but are expired.
- It would return to the caller a list of these keys.

There are two possible issues that I'm seeing with this approach:
1. If the entry was deleted from soroban-rpc, and is available only on ESS, that won't work.
2. If a smart contract would "test" the existence of another ledger entry ( i.e. read-only ), the output of the simulate would be as if it's *required*.  example for that would be a contract that has no data, and would create it's own data after the first/second invocation.

**Comment by dmkozh** [comment]
> The soroban-rpc would treat all entries as "live" entries.

To be clear, 'treat as live' means 'update the expiration ledger to be live before returning the value to host from the callback'.

> If the entry was deleted from soroban-rpc, and is available only on ESS, that won't work.

Sure, we obviously can't use an entry that isn't stored by soroban-rpc. This can only be a best-effort feature, depending on the eviction policy of soroban-rpc db. For the evicted entries core will store a bloom filter, probably soroban-rpc would need to do the same.

> If a smart contract would "test" the existence of another ledger entry ( i.e. read-only ), the output of the simulate would be as if it's required. example for that would be a contract that has no data, and would create it's own data after the first/second invocation.

Not sure I understand. Any ledger access (even a simple `has` check) has to be reflected in the snapshot. Again, from the host/contract standpoint there are no expired entries, there are only entries that exist or don't exist (as specified by the snapshot provider). It's the responsibility of core/soroban-rpc to provide the correct information. So if no expired entries are involved, then everything will work just fine. If there are expired entries, then core/soroban-rpc need to take a corresponding action.

**Comment by tsachiherman** [comment]
I think that the tldr of what you're describing above is that the soroban-rpc can only provide feedback on accessed expired entries. It is for the caller of the simulateTransaction to understand the meaning behind the contract, since:
1. A contract can fail due to a missing ledger entry; but it can also fail due to an existence of a ledger entry.
2. A contract can succeed regardless of the existence of a missing ledger entry.
3. The error returned by a contract doesn't indicate whether a required entry was missing.
4. The number of missing entries is undefined, as contract can change it's behavior per the existence of an entry.

Proving a "hint" on expired ledger entries is not very definitive. There might be no better option though.

**Comment by dmkozh** [comment]
I think you're confusing the terms here. 'Missing' entry is an entry for which we can say 'this entry does not exist in the ledger'. Contracts indeed might have different behavior depending on entries being missing or present - but this has nothing to do with expiration. Expired entries are not missing entries and they shouldn't in any way affect the contract logic.
I think returning as many expired ledger entries as possible is good enough (and I'm not sure if there are better options even in theory).

**Comment by paulbellamy** [comment]
Could we list some terminology here to clarify the discussion?
- "missing" == never existed on chain, or was explicitly deleted. `has(key) -> false`
- "expired" == past it's TTL, but still in-memory in core + rpc. `has(key) -> exception`
  - Should be indistinguishable from an evicted entry, afaik.
- "evicted" == only in ESS. `has(key) -> exception`

I don't think it's generally possible to return more than one expired/evicted LedgerKey from a single `simulateTransaction`. My assumption is that the contract is loading the LedgerEntry in order to read the data and make some decision based on that data. So, continuing contract execution past an evicted entry load is not really possible (since rpc won't have the data). We can show the data for expired entries and continue execution, but I'm not really convinced that is a good idea because it makes a weird distinction between expired/evicted that isn't relevant for the client (afaik).

**Comment by dmkozh** [comment]
"expired" and "evicted" is the same thing semantically and ideally we shouldn't distinguish between these. Otherwise, this looks correct.

FWIW evictions shouldn't necessarily correlate between bucket list and soroban-rpc DB and might have different eviction schedules and rules. The only requirement is that both should maintain some index of evicted keys (when there are evictions). 

I still think it's better to provide 'best-effort' service for returning as many expired keys as possible. I would also expect this 'best effort' to work really well most of the time, because it's much more likely that a user hits a recently expired entry and not something that has been expired for, say, more than a year. I don't think it's too confusing - we can just say 'these keys have definitely expired, but there might be more', which is a general caveat about using preflight (it never can guarantee that exactly the same thing will happen on-chain).

**Comment by paulbellamy** [comment]
> "expired" and "evicted" is the same thing semantically and ideally we shouldn't distinguish between these. Otherwise, this looks correct.

From a user-perspective, I agree. But I think it might be causing some confusion for us in this discussion right now, so wanted to highlight the difference for clarity.

> I still think it's better to provide 'best-effort' service for returning as many expired keys as possible. I would also expect this 'best effort' to work really well most of the time,

Yeah, as long as we're clear it's "best-effort" that seems fine. My expectation is that it wouldn't really do much most of the time, because entries would either be "live" and frequently access, or *very* expired, and almost never accessed. But that's just a guess!

**Comment by dmkozh** [comment]
> because entries would either be "live" and frequently access, or very expired, and almost never accessed

These 'never accessed' entries don't have a high chance to occur in preflight as well. This is mostly for the newer deployments that weren't bumped for whatever reason - expiration proved to be a big problem on futurenet and I would expect the same on mainnet.
