### ISSUE TITLE
soroban-cli: should return non-zero exit code when can't find data

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/soroban-tools#920]
### What version are you using?

- stellar/soroban-tools@b1519a4d90502ce3155960541b2a98c88f3dd043 (rpc and cli)
- stellar/stellar-core@22b9bb38416e5ce058eb9c1fadfdd414a4661833
- stellar/rs-soroban-env@eb5a9ba053a7b64a8eff605db625525378f7bea0

### What did you do?

```console
❯ soroban contract read --network local --source me --id CAW7SH5JG45U6YLCFB6YD2KVSOZQHMNEJQPN6KDZOCGSXWR72ZIFBBMP --key abc
```

### What did you expect to see?

An error because no contract data or ledger entry is stored with that key.

### What did you see instead?

Nothing. No output.

### Discussion

It's difficult to compose tools that don't exit with a non-zero code in failure cases.

From a UX point-of-view the user can be left feeling uneasy when a tool returns or outputs nothing.
```[tasklist]
### Tasks
- [ ] https://github.com/stellar/soroban-tools/pull/923
- [ ] https://github.com/stellar/soroban-tools/pull/924
```

**Comment by willemneal** [comment]
The exit code issue is also noted here: https://github.com/stellar/soroban-tools/issues/774 

Currently in the main.rs when doing a `run` it catches the error and prints it, but doesn't exit with a non-zero code. So this seems like two issues. I agree that there should be a proper error, but I think we should also exit with a non-zero so that scripts and other programs invoking the CLI will know there has been an error.

**Comment by tsachiherman** [comment]
I agree with @willemneal here. The fact that the empty group isn't being reported as an error in this particular case is an issue - but not the *same* issue not setting the exit code to 1. Let's tackle these separately ?
